---
title: "In-class Exercise 7"
date: "March 8,2024"
date-modified: "last-modified"
toc: true
execute: 
  eval: true
  echo: true
  warning: false
  message: false
  code-fold: false
---

```{r}
pacman::p_load(sf,terra,gstat,tmap,
               viridis,tidyverse)
```

```{r}
rfstations <- read_csv("data/aspatial/RainfallStation.csv")

```

```{r}
rfdata <- read_csv("data/aspatial/DAILYDATA_202402.csv") %>%
  select (c(1,5)) %>%
  group_by(Station) %>%
  summarise(MONTHSUM= sum(`Daily Rainfall Total (mm)`)) %>%
  ungroup()
```

```{r}
rfdata <- rfdata %>%
  left_join(rfstations)

```

```{r}
rfdata_sf <- st_as_sf(rfdata,
                      coords = c("Longitude",
                                 "Latitude"),
                      crs=4326) %>%
  st_transform(crs=3414)
```


```{r}
mpsz2019 <- st_read(dsn="data/geospatial",
                    layer="MPSZ-2019") %>%
  st_transform(crs=3414)
```
```{r}
tmap_options(check.and.fix=TRUE)
tmap_mode("view")
tm_shape(mpsz2019)+
  tm_borders()+
tm_shape(rfdata_sf)+
  tm_dots(col='MONTHSUM')
tmap_mode("plot")

```

```{r}
grid <- terra::rast(mpsz2019,
                    nrows= 690,
                    ncols= 1075)

xy <- terra::xyFromCell(grid,
                        1:ncell(grid))
```

```{r}
coop <- st_as_sf(as.data.frame(xy),
                 coords = c("x","y"),
                 crs =st_crs(mpsz2019))
coop <- st_filter(coop,mpsz2019)
```

```{r}
res <- gstat(formula= MONTHSUM ~ 1,
             locations =rfdata_sf,
             nmax= 15,
             set = list(idp = 0))
resp <- predict(res,coop)
resp$x <- st_coordinates(resp)[,1]
resp$y <- st_coordinates(resp)[,2]
resp$pred <- resp$var1.pred

pred <-terra:: rasterize(resp, grid,
                         field="pred",
                         fun="mean")
```

```{r}
tmap_options(check.and.fix = TRUE)
tmap_mode("plot")
tm_shape(pred)+
  tm_raster(alpha=0.6,
            palette = "viridis")
```











```
